### ISSUE TITLE
Deletions are not tracked

### ISSUE THREAD

**Issue by peter-parker-git** [kikijiki/ntfs-reader#2]
There is a bug in the USN library. When a folder is deleted, it causes the file paths inside the folder to not display correctly.

I have a file on my Z drive at Z:\demo\2\bed.jpg. When I delete the folder Z:\demo\2, the files inside this folder are also deleted. Below is my test code.

```
extern crate ntfs;

use ntfs::journal::{Journal, JournalOptions};
use ntfs::volume::Volume;

fn main() -> std::io::Result<()> {
    let volume = match Volume::new("\\\\?\\Z:") {
        Ok(v) => v,
        Err(e) => {
            println!("error: {:?}", e);
            return Ok(());
        }
    };

    let mut journal = Journal::new(volume, JournalOptions::default())?;

    loop {
        let records = journal.read()?;
        for record in records {
            println!("change: {:?}", record);
        }
        std::thread::sleep(std::time::Duration::from_secs(3));
    }
}
```

The run result is:
change: UsnRecord { usn: 36176, timestamp: 13350091285.7853214s, file_id: 4785074604081198, parent_id: 4785074604081197, reason: 2147484160, path: "bed.jpg" }
change: UsnRecord { usn: 36256, timestamp: 13350091285.7853214s, file_id: 4785074604081197, parent_id: 844424930132012, reason: 2147484160, path: "\\?\Z:\demo\2" }

It is evident that the file path for bed.jpg inside the folder is not correctly printed as z:\demo\2\bed.jpg. Can you fix this bug? Thank you.

**Comment by peter-parker-git** [comment]
Hello @kikijiki would you mind to take a look the above bug? Thank you.

**Comment by kikijiki** [comment]
Hey thanks for the bug report.

I think that by the time the journal tries to compute the path, it has already been deleted and so it fails.
To fix that the journal would need to track deletions too in the history, like it already does for moves:

```rust
if record.reason
    & (Ioctl::USN_REASON_RENAME_OLD_NAME
        | Ioctl::USN_REASON_HARD_LINK_CHANGE
        | Ioctl::USN_REASON_REPARSE_POINT_CHANGE
        | Ioctl::USN_REASON_FILE_DELETE) // <-- Add
    != 0
{
```

And then add some logic to `get_usn_record_path`/`get_file_path`.
Sounds reasonable, I'll take a stab at it when I have some time.

**Comment by peter-parker-git** [comment]
> Hey thanks for the bug report.
> 
> I think that by the time the journal tries to compute the path, it has already been deleted and so it fails. To fix that the journal would need to track deletions too in the history, like it already does for moves:
> 
> ```rust
> if record.reason
>     & (Ioctl::USN_REASON_RENAME_OLD_NAME
>         | Ioctl::USN_REASON_HARD_LINK_CHANGE
>         | Ioctl::USN_REASON_REPARSE_POINT_CHANGE
>         | Ioctl::USN_REASON_FILE_DELETE) // <-- Add
>     != 0
> {
> ```
> 
> And then add some logic to `get_usn_record_path`/`get_file_path`. Sounds reasonable, I'll take a stab at it when I have some time.

@kikijiki  Thank you for your reply. I tried adding the line of code "| Ioctl::USN_REASON_FILE_DELETE" as you suggested to see if it could fix the problem, but unfortunately, adding just this line does not solve the issue. It seems that modifying the get_usn_record_path/get_file_path functions might be necessary to fix this problem. I have a limited understanding of the Windows underlying USN and my attempt to fix it myself failed. If you have the time, I would greatly appreciate your help in resolving this. Thank you very much.

**Comment by kikijiki** [comment]
Yeah just adding that won't be enough unfortunately.
I'll post an update when I have something working.

**Comment by kikijiki** [comment]
I took some time to think about it but I don't think this is easily fixable, my original suggestion was wrong.

By the time the journal is processed, both the directory and the files inside will be already gone, and it's too late to compute the path (or save it in the history). You would need to manually recompute the parent's path using file_id/path map that you maintain, or maybe using cached MFT records.
If it's a specific folder you are monitoring, it would be easier to use a file watcher.

In any case, it doesn't seem like something you can implement in the journal directly unfortunately.
Unless there is some solution I overlooked, I'll have to close this.

**Comment by peter-parker-git** [comment]
> I took some time to think about it but I don't think this is easily fixable, my original suggestion was wrong.
> 
> By the time the journal is processed, both the directory and the files inside will be already gone, and it's too late to compute the path (or save it in the history). You would need to manually recompute the parent's path using file_id/path map that you maintain, or maybe using cached MFT records. If it's a specific folder you are monitoring, it would be easier to use a file watcher.
> 
> In any case, it doesn't seem like something you can implement in the journal directly unfortunately. Unless there is some solution I overlooked, I'll have to close this.

@kikijiki Based on my understanding, it is feasible, as I have tested USN libraries written in other languages, and they can display the complete path even when a file is deleted. When I tested other libraries, they were able to input the USN ID of files that had already been deleted and successfully query their information.

My guess is that there might be an issue with the parameters passed to the Windows API, which refuses to query a USN ID for a deleted file, resulting in an incomplete path. I'm not familiar with these low-level Windows APIs; otherwise, I could have fixed it myself and submitted a merge request for the code.

**Comment by kikijiki** [comment]
In theory the file should not be immediately deleted, the MFT record should still exist and be flagged as not in use 🤔

Knowing the file id it should be possible to access that record with the name still cached, then you would need to keep processing all the parents to compute the whole path though.

**Comment by kikijiki** [comment]
I'll reopen this since it's a valid request, as you said there should be some way of doing it.
Still not sure how to implement it though.
The MFT class has a function to read a record directly from the fs but it could be very slow.

**Comment by peter-parker-git** [comment]
> I'll reopen this since it's a valid request, as you said there should be some way of doing it. Still not sure how to implement it though. The MFT class has a function to read a record directly from the fs but it could be very slow.


@kikijiki  I know how they do it, and I have an example in Go language here. But please note that they are using USN_RECORD_V2, while you are using USN_RECORD_V3. My limited understanding of Windows low-level APIs is the reason why I don't know what additional parameters need to be passed for V3 compared to V2 to enable it to read already deleted USN IDs. This is why I am unable to modify your library based on this code.

In the entire process, you don't need to read the MFT; you just need to focus on the USN, because the example I provided only reads the USN and never read the MFT. My sample code can read a deleted USN ID, then find its parent node, and then read the USN information of the parent node again, all the way up to the root directory. This is the core principle. The current issue is how to pass certain parameters in V3 to enable it to read deleted USN IDs. Hope this help.

Please check the example code below.
https://github.com/y4v8/filewatcher/blob/1a16ffa8c63a176b65c3202eb1daefc75ac0a037/watcher.go#L147

**Comment by kikijiki** [comment]
Thanks for the reference.

It's using the record only to retrieve the file_id, that information is in V3 too (V2 and V3 are almost identical).
The main difference seems to be that instead of getting the full path from the API (which does not work for deleted files), it requests only the name and then it computes the path by itself.

It is reading the MFT with `GetFileNameByID` though, similarly to what `MFT::get_record_fs()` does, but through the Windows API. I guess that still works because the name is stored directly in the record (which persists after the file is "deleted"), while the API to get the full path I am using now fails in that case.

Anyway we can do something similar then. I'm not sure if it should be done that way by default or only when the existing method fails. I'll try to do some profiling.

**Comment by peter-parker-git** [comment]
> Thanks for the reference.
> 
> It's using the record only to retrieve the file_id, that information is in V3 too (V2 and V3 are almost identical). The main difference seems to be that instead of getting the full path from the API (which does not work for deleted files), it requests only the name and then it computes the path by itself.
> 
> It is reading the MFT with `GetFileNameByID` though, similarly to what `MFT::get_record_fs()` does, but through the Windows API. I guess that still works because the name is stored directly in the record (which persists after the file is "deleted"), while the API to get the full path I am using now fails in that case.
> 
> Anyway we can do something similar then. I'm not sure if it should be done that way by default or only when the existing method fails. I'll try to do some profiling.

@kikijiki Yes, that's right, this code calculates the full path by obtaining the file names at each level.

Indeed, you can consider adopting this approach to retrieve the full path of deleted files when the existing method fails.

You might not need to worry too much about efficiency issues, as there won't be a large number of deletions at the same time in the Windows system. Even if this method is fully adopted, no problems have arisen during testing on my machine.

**Comment by kikijiki** [comment]
The path computation is required for all events, not only deletions.
This new method could be used for all events, only for deletions, or only when the current one fails.

**Comment by kikijiki** [comment]
It could be more robust in general though.
Even if it's not a deletion event, it could be that at the time of reading the journal the file got deleted in the meantime, and that would make the path fail.
So it's not just for deletions, the question is if we should do the path computation loop always or just when `GetFileInformationByHandleEx` fails.

**Comment by kikijiki** [comment]
Actually after reading the code a bit, it's not doing a loop there.
It only handles 2 cases, either `GetFilenamebyID` works on the file, or it does `GetFilenameByID` on the parent and appends the current record name.
I thought `GetFilenameByID` was a Windows API thing, but not:

```go
func GetFileNameByID(hVolume syscall.Handle, fileID uint64) (string, error) {
	fd := FILE_ID_DESCRIPTOR{}
	fd.DwSize = uint32(unsafe.Sizeof(fd))
	fd.FileId = fileID

	h, err := OpenFileById(hVolume,
		&fd,
		0,
		syscall.FILE_SHARE_READ|syscall.FILE_SHARE_WRITE|syscall.FILE_SHARE_DELETE,
		nil,
		syscall.FILE_FLAG_BACKUP_SEMANTICS)
	if err != nil {
		return "", errors.Wrap(err)
	}
	defer syscall.CloseHandle(h)

	fileNameInfo := FILE_NAME_INFO{}
	sizeFileNameInfo := uint32(unsafe.Sizeof(fileNameInfo))
	err = GetFileInformationByHandleEx(h, FILE_NAME_INFO_BY_HANDLE, unsafe.Pointer(&fileNameInfo), sizeFileNameInfo)
	if err == syscall.ERROR_MORE_DATA {

		sizeFileNameInfo = (4 + fileNameInfo.FileNameLength) / 2
		buf := make([]uint16, sizeFileNameInfo)
		err = GetFileInformationByHandleEx(h, FILE_NAME_INFO_BY_HANDLE, unsafe.Pointer(&buf[0]), sizeFileNameInfo*2)

		if err == nil {
			return syscall.UTF16ToString(buf[2 : 2+fileNameInfo.FileNameLength/2]), nil
		}
	}
	if err != nil {
		return "", errors.Wrap(err)
	}

	return syscall.UTF16ToString(fileNameInfo.FileName[0 : fileNameInfo.FileNameLength/2]), nil
}
```

It uses `GetFileInformationByHandleEx`, which I am already using...

**Comment by kikijiki** [comment]
This could be the reason it's working there, I'm not using this flag

<img width="491" alt="image" src="https://github.com/kikijiki/ntfs-reader/assets/784077/487ebbf1-992c-4960-bc02-d2df104c1947">

**Comment by kikijiki** [comment]
Also I am using `FILE_GENERIC_READ`, but passing `0` might be better too.

<img width="493" alt="image" src="https://github.com/kikijiki/ntfs-reader/assets/784077/36f72c0c-ea74-48de-af20-258492ef2069">

**Comment by kikijiki** [comment]
Also I'm not handling the `ERROR_MORE_DATA` case.

**Comment by kikijiki** [comment]
I tried adding all three changes but still have the same issue as before 🤔

**Comment by kikijiki** [comment]
I made a draft PR in the meantime.

**Comment by hkhk368** [comment]
> I tried adding all three changes but still have the same issue as before 🤔

@kikijiki Unfortunately, you are still encountering the same problem. Perhaps the usage of V3 and V2 is different? I don't quite understand the specific differences in usage, although we know V3 is better. But maybe we should consider switching to V2?

**Comment by peter-parker-git** [comment]
> I made a draft PR in the meantime.

@kikijiki Yes, I agree with his opinion. If V3 can't solve this issue, perhaps we can switch to using V2, and then directly convert the Go code into Rust. Thanks.

**Comment by kikijiki** [comment]
In #4 I added support for V2. Every test runs both for V2 and V3.

Unfortunately in my local tests both are failing for deletions.

```
test journal::test::file_create_v2 ... ok
test journal::test::file_create_v3 ... ok
test journal::test::file_move_v2 ... ok
test journal::test::file_move_v3 ... ok
test journal::test::file_delete_v2 ...  WARN ntfs_reader::journal: Could not get path: usn-journal-test-delete.txt
The file deletion was not detected
FAILED
test journal::test::file_delete_v3 ...  WARN ntfs_reader::journal: Could not get path: usn-journal-test-delete.txt
The file deletion was not detected
FAILED
```

**Comment by peter-parker-git** [comment]
> In #4 I added support for V2. Every test runs both for V2 and V3.
> 
> Unfortunately in my local tests both are failing for deletions.
> 
> ```
> test journal::test::file_create_v2 ... ok
> test journal::test::file_create_v3 ... ok
> test journal::test::file_move_v2 ... ok
> test journal::test::file_move_v3 ... ok
> test journal::test::file_delete_v2 ...  WARN ntfs_reader::journal: Could not get path: usn-journal-test-delete.txt
> The file deletion was not detected
> FAILED
> test journal::test::file_delete_v3 ...  WARN ntfs_reader::journal: Could not get path: usn-journal-test-delete.txt
> The file deletion was not detected
> FAILED
> ```

I don't know why switching to V2 still doesn't work. Could it be because of the RUST language? The same code runs fine in GO language.

There's a phenomenon I'd like to share with you, which might be helpful. In the test code at the top of this post, if you remove the following line, it causes a dead loop, but then it can display the complete path normally. However, the cost of doing this is 100% CPU usage on one core.
 std::thread::sleep(std::time::Duration::from_secs(3));

**Comment by kikijiki** [comment]
One last difference I see is that the go library uses overlapped IO to do asynchronous operations.
I can try using it too to see if it helps.

**Comment by kikijiki** [comment]
I tried adding it in the same PR but still failing 🤔 
I must be missing something.

**Comment by stevenhuyn** [comment]
I'm gonna try to peek at other implementations as well!

https://gist.github.com/pkrnjevic/7219861

https://github.com/forensicmatt/RustyUsn/blob/master/src/bin/listen_usn.rs

https://github.com/Horbin-Magician/rotor/blob/594a041f451fe4a7639ea44b4c9230bc937c88d9/src/module/searcher/volume.rs#L406

**Comment by kikijiki** [comment]
I think this might be related to the timing of the deletions.

As an experiment I tried pulling https://github.com/y4v8/filewatcher and adding this bit in main.go:

```go
	for event := range events {
		if event.Reason&win.USN_REASON_FILE_DELETE != 0 {
			if strings.Contains(event.Name, "dummy") {
				log.Println(event.Name, reasonNames(event.Reason))
			}
		}
	}
```

While this was "watching" I run `cargo test` on this library. In the test I create a file `c:\dummy\dummy_file.txt` and then delete the parent directory `c:\dummy`. The result is that the go library manages to obtain the path correctly only 2 out of 10 times:

```
2024/03/31 09:24:53 c:\\dummy FILE_DELETE
2024/03/31 09:24:56 c:\\dummy FILE_DELETE
2024/03/31 09:24:57 c:\\dummy FILE_DELETE
2024/03/31 09:24:58 c:\\dummy FILE_DELETE
2024/03/31 09:24:59 c:\\dummy FILE_DELETE
2024/03/31 09:25:00 c:\dummy\dummy_file.txt FILE_DELETE
2024/03/31 09:25:00 c:\\dummy FILE_DELETE
2024/03/31 09:25:03 c:\\dummy FILE_DELETE
2024/03/31 09:25:06 c:\dummy\dummy_file.txt FILE_DELETE
2024/03/31 09:25:07 c:\\dummy FILE_DELETE
2024/03/31 09:25:08 c:\\dummy FILE_DELETE
2024/03/31 09:25:09 c:\\dummy FILE_DELETE
```

But if I delete the directory from Go instead it always works well. So I think it might be a combination of two things:
- Go uses a separate thread that continuously runs in the background, and is able to process events in the middle of the `RemoveAll` (the directory is the last thing that gets deleted, so it still exists for the deleted files).
- Rust's `std::fs::remove_dir_all()` is faster than Go's `os.RemoveAll()` so the chances of getting the parent directory path before it gets deleted are lower.

**Comment by kikijiki** [comment]
So the solution would be to have this watcher run on a separate thread in an infinite loop continuously reading the journal.
It should start before the directly is deleted, so that it can process the file deletion before the parent deletion happens.
And it would need to be lucky enough with the timing I guess.

This is not really _fixed_ but it's not something that this library is supposed to implement. The journal reading function is available but how it is invoked (sync or async, continuous or chunked, etc.) is left to the user's specific use case.

**Comment by peter-parker-git** [comment]
> So the solution would be to have this watcher run on a separate thread in an infinite loop continuously reading the journal. It should start before the directly is deleted, so that it can process the file deletion before the parent deletion happens. And it would need to be lucky enough with the timing I guess.
> 
> This is not really _fixed_ but it's not something that this library is supposed to implement. The journal reading function is available but how it is invoked (sync or async, continuous or chunked, etc.) is left to the user's specific use case.

While running the watcher in a separate thread with an infinite loop might seem like a workaround, but it could consume 100% of a CPU core, which isn't an efficient solution. 

Actually, there is another solution that will definitely solve this issue, though it will increase memory usage. We could create a map where the key is the USN ID, and it includes the filename and parent USN ID. When a file needs to be deleted, we can retrieve the complete path from the map through a step-by-step query, print the full path of the file to be deleted, and then remove the corresponding node from the map.

**Comment by kikijiki** [comment]
@peter-parker-git That would work only for files that get created after the watcher starts monitoring the journal. Even if you set the option to process the journal from the start, the journal has finite size so it will contain only file creations of the past few hours/days.

To make it work properly you would need to initialize the map by first scanning the MFT and then keeping it up to date with journal events. More realistically, you could initialize it only with the files of some folder you are interested in, instead of the whole volume (so just a file walk instead of loading the MFT).

**Comment by peter-parker-git** [comment]
> @peter-parker-git That would work only for files that get created after the watcher starts monitoring the journal. Even if you set the option to process the journal from the start, the journal has finite size so it will contain only file creations of the past few hours/days.
> 
> To make it work properly you would need to initialize the map by first scanning the MFT and then keeping it up to date with journal events. More realistically, you could initialize it only with the files of some folder you are interested in, instead of the whole volume (so just a file walk instead of loading the MFT).


@kikijiki Hello, you might have misunderstood. The specific approach is that when the program starts, it scans the entire hard drive for the USN IDs of all files and records the file USN ID, names and parent node USN ID, then stores them in a map as I just described. 

Next, it starts listening for USN changes, checking every 500 milliseconds for the latest changes. For example, if a folder is deleted and many files within it are also deleted, the path may not be correctly retrieved due to the folder's deletion. 

However, this is not a problem as our in-memory map acts like a complete backup, allowing us to find the full path using the parent USN ID and display it. Since the files are deleted, our task is to remove the corresponding USN IDs from the map. This method ensures that a complete path can be outputted. I have a 2TB hard drive, and using this method only takes up a few dozen megabytes of memory (I conducted tests using Go based on the Go example link I shared with you earlier).

**Comment by kikijiki** [comment]
That's what I said basically, I think you are confusing the file reference number with the USN though.

**Comment by peter-parker-git** [comment]
> Owner

Thank you for clarifying. I thought that the USN log queried in the following way (in Go language) could contain all the USN changes on a disk. If this method can only scan recent changes, such as from the past few days, then indeed, scanning the entire MFT is necessary.

`err = syscall.DeviceIoControl(volumeHandle, IOCTL_FSCTL_QUERY_USN_JOURNAL, nil, 0, (*byte)(unsafe.Pointer(&queryUSNData)), uint32(unsafe.Sizeof(queryUSNData)), &bytesReturned, nil)
	if err != nil {
		log.Fatalf("Failed to query USN journal: %v", err)
	}
`

Can you tell me how to correlate a file’s USN record with its MFT record? The only method I can think of is relying on the file path. From my understanding, an MFT record does not contain the USN information of the file, and similarly, when a file is modified, the USN record does not contain a reference to the MFT. Only by using the complete path can the two be linked. Then, when a file is deleted, I would know which MFT record needs to be removed from memory. Is there another way?

**Comment by kikijiki** [comment]
Both the MFT record and USN record should contain the file id/number, if you use V3 you might have to convert the 128bit reference to 64.
