### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by tuolaji123** [kikijiki/ntfs-reader#3]
In the test code for reading the USN (Update Sequence Number) journal, the newly created files can be read, but manually created files and downloaded files cannot be read. I'm not sure what the reason is.

```rust
    #[test]
    fn file_create() -> NtfsReaderResult<()> {
        let volume = Volume::new("\\\\?\\C:")?;
        let mut journal = Journal::new(volume, JournalOptions::default())?;
        let _ = journal.read()?;

        // Make sure there is something to read.
        // for x in 0..10 {
        //     let path = std::env::temp_dir().join(format!("usn-journal-test-{}.txt", x));
        //     File::create(path)?.write_all(b"test")?;
        // }

        let results = journal.read()?;
        // assert!(results.len() >= 10);
        println!("usn：{:?}", results);

        Ok(())
    }
```

**Comment by hkhk368** [comment]
@tuolaji123 

I noticed that you are working on something related to USN. Have you encountered the same issue as the one in the link below? Thank you.

https://github.com/kikijiki/ntfs-reader/issues/2

**Comment by kikijiki** [comment]
With default settings it will start reading from the end of the journal at the time you create it.
If the file was created earlier than that it will not appear.
Maybe you want to specify a different `JournalOptions` for `NextUsn`?
Also by default the journal only reads a fixed amount of data, so you should make sure that you keep reading until you get to that event.
