### ISSUE TITLE
I am a beginner in Rust and have a hard time reading the source code, can you provide some examples of how to use it?

### ISSUE THREAD

**Issue by initialencounter** [kikijiki/ntfs-reader#5]

**Comment by kikijiki** [comment]
Take a look at the tests.

How to read/scan the MFT: https://github.com/kikijiki/ntfs-reader/blob/master/src/mft.rs#L236

How to read journal changes: https://github.com/kikijiki/ntfs-reader/blob/master/src/journal.rs#L545

I'll add some docs at some point, if you need anything more specific let me know.

**Comment by kikijiki** [comment]
I updated the readme with a usage section.
